# Generated by Django 5.0.1 on 2024-01-14 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_id', models.CharField(blank=True, max_length=12)),
                ('date', models.DateField(blank=True)),
                ('quantity', models.IntegerField(blank=True)),
                ('hours_taken', models.IntegerField(blank=True)),
                ('operator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='employees.operator')),
                ('product', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Inventary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_quantity', models.IntegerField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('productions', models.ManyToManyField(to='products.production')),
            ],
        ),
    ]
