# Generated by Django 5.0.1 on 2024-01-16 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_production_inventary'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='notes',
            field=models.TextField(default='No Notes'),
        ),
    ]
